import { getInsightResult } from "@/lib/insights/get-insight-result";

export async function InsightsActionsSlot() {
  const { result, aggregated } = await getInsightResult();

  if (aggregated.total === 0) {
    return (
      <p className="text-sm text-[var(--staff-ink)]/50 text-center py-8">
        No data yet — suggested actions will appear once residents check in.
      </p>
    );
  }

  return (
    <div className="space-y-4">
      <ul className="space-y-3">
        {result.suggested_actions.map((item, i) => (
          <li
            key={i}
            className="rounded-xl border border-[var(--staff-ink)]/10 bg-[var(--staff-input-bg)]/50 px-4 py-3"
          >
            <p className="text-sm font-medium text-[var(--staff-ink)]">{item.action}</p>
            <p className="mt-0.5 text-xs text-[var(--staff-ink)]/60">{item.reason}</p>
          </li>
        ))}
      </ul>

      <div className="rounded-xl border border-amber-200/60 bg-amber-50/60 px-4 py-3">
        <p className="text-xs font-semibold uppercase tracking-wide text-amber-800 mb-1">
          Watch out for
        </p>
        <p className="text-sm text-amber-900">{result.watch_out_for}</p>
      </div>

      <p className="text-xs text-[var(--staff-ink)]/40">
        {process.env.AI_PROVIDER === "claude"
          ? "Generated by Claude AI"
          : "Rule-based analysis"}
        {" "}· past 24 hours
      </p>
    </div>
  );
}
